module.exports = {
    sync: function(models, callback){
        var TimeZone = models.TimeZone;
        
        TimeZone.sync().then(function(){
            TimeZone.count().then(function(TimeZones){
                if(TimeZones === 0){
                    TimeZone.bulkCreate(TimeZonesToCreate).then(function(){
                        console.log("Timezones created successfully!");
                        callback && callback();
                    });
                }else{
                    callback && callback();
                }
            });
        });
    }
};

var TimeZonesToCreate = [{name:"(GMT0:00) Greenwich Mean Time (Africa/Abidjan)", code:"Africa/Abidjan"},
{name:"(GMT0:00) Ghana Mean Time (Africa/Accra)", code:"Africa/Accra"},
{name:"(GMT+3:00) Eastern African Time (Africa/Addis_Ababa)", code:"Africa/Addis_Ababa"},
{name:"(GMT+1:00) Central European Time (Africa/Algiers)", code:"Africa/Algiers"},
{name:"(GMT+3:00) Eastern African Time (Africa/Asmara)", code:"Africa/Asmara"},
{name:"(GMT+3:00) Eastern African Time (Africa/Asmera)", code:"Africa/Asmera"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Bamako)", code:"Africa/Bamako"},
{name:"(GMT+1:00) Western African Time (Africa/Bangui)", code:"Africa/Bangui"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Banjul)", code:"Africa/Banjul"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Bissau)", code:"Africa/Bissau"},
{name:"(GMT+2:00) Central African Time (Africa/Blantyre)", code:"Africa/Blantyre"},
{name:"(GMT+1:00) Western African Time (Africa/Brazzaville)", code:"Africa/Brazzaville"},
{name:"(GMT+2:00) Central African Time (Africa/Bujumbura)", code:"Africa/Bujumbura"},
{name:"(GMT+2:00) Eastern European Time (Africa/Cairo)", code:"Africa/Cairo"},
{name:"(GMT0:00) Western European Time (Africa/Casablanca)", code:"Africa/Casablanca"},
{name:"(GMT+1:00) Central European Time (Africa/Ceuta)", code:"Africa/Ceuta"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Conakry)", code:"Africa/Conakry"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Dakar)", code:"Africa/Dakar"},
{name:"(GMT+3:00) Eastern African Time (Africa/Dar_es_Salaam)", code:"Africa/Dar_es_Salaam"},
{name:"(GMT+3:00) Eastern African Time (Africa/Djibouti)", code:"Africa/Djibouti"},
{name:"(GMT+1:00) Western African Time (Africa/Douala)", code:"Africa/Douala"},
{name:"(GMT0:00) Western European Time (Africa/El_Aaiun)", code:"Africa/El_Aaiun"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Freetown)", code:"Africa/Freetown"},
{name:"(GMT+2:00) Central African Time (Africa/Gaborone)", code:"Africa/Gaborone"},
{name:"(GMT+2:00) Central African Time (Africa/Harare)", code:"Africa/Harare"},
{name:"(GMT+2:00) South Africa Standard Time (Africa/Johannesburg)", code:"Africa/Johannesburg"},
{name:"(GMT+3:00) Eastern African Time (Africa/Juba)", code:"Africa/Juba"},
{name:"(GMT+3:00) Eastern African Time (Africa/Kampala)", code:"Africa/Kampala"},
{name:"(GMT+3:00) Eastern African Time (Africa/Khartoum)", code:"Africa/Khartoum"},
{name:"(GMT+2:00) Central African Time (Africa/Kigali)", code:"Africa/Kigali"},
{name:"(GMT+1:00) Western African Time (Africa/Kinshasa)", code:"Africa/Kinshasa"},
{name:"(GMT+1:00) Western African Time (Africa/Lagos)", code:"Africa/Lagos"},
{name:"(GMT+1:00) Western African Time (Africa/Libreville)", code:"Africa/Libreville"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Lome)", code:"Africa/Lome"},
{name:"(GMT+1:00) Western African Time (Africa/Luanda)", code:"Africa/Luanda"},
{name:"(GMT+2:00) Central African Time (Africa/Lubumbashi)", code:"Africa/Lubumbashi"},
{name:"(GMT+2:00) Central African Time (Africa/Lusaka)", code:"Africa/Lusaka"},
{name:"(GMT+1:00) Western African Time (Africa/Malabo)", code:"Africa/Malabo"},
{name:"(GMT+2:00) Central African Time (Africa/Maputo)", code:"Africa/Maputo"},
{name:"(GMT+2:00) South Africa Standard Time (Africa/Maseru)", code:"Africa/Maseru"},
{name:"(GMT+2:00) South Africa Standard Time (Africa/Mbabane)", code:"Africa/Mbabane"},
{name:"(GMT+3:00) Eastern African Time (Africa/Mogadishu)", code:"Africa/Mogadishu"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Monrovia)", code:"Africa/Monrovia"},
{name:"(GMT+3:00) Eastern African Time (Africa/Nairobi)", code:"Africa/Nairobi"},
{name:"(GMT+1:00) Western African Time (Africa/Ndjamena)", code:"Africa/Ndjamena"},
{name:"(GMT+1:00) Western African Time (Africa/Niamey)", code:"Africa/Niamey"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Nouakchott)", code:"Africa/Nouakchott"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Ouagadougou)", code:"Africa/Ouagadougou"},
{name:"(GMT+1:00) Western African Time (Africa/Porto-Novo)", code:"Africa/Porto-Novo"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Sao_Tome)", code:"Africa/Sao_Tome"},
{name:"(GMT0:00) Greenwich Mean Time (Africa/Timbuktu)", code:"Africa/Timbuktu"},
{name:"(GMT+2:00) Eastern European Time (Africa/Tripoli)", code:"Africa/Tripoli"},
{name:"(GMT+1:00) Central European Time (Africa/Tunis)", code:"Africa/Tunis"},
{name:"(GMT+1:00) Western African Time (Africa/Windhoek)", code:"Africa/Windhoek"},
{name:"(GMT-10:00) Hawaii-Aleutian Standard Time (America/Adak)", code:"America/Adak"},
{name:"(GMT-9:00) Alaska Standard Time (America/Anchorage)", code:"America/Anchorage"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Anguilla)", code:"America/Anguilla"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Antigua)", code:"America/Antigua"},
{name:"(GMT-3:00) Brasilia Time (America/Araguaina)", code:"America/Araguaina"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Buenos_Aires)", code:"America/Argentina/Buenos_Aires"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Catamarca)", code:"America/Argentina/Catamarca"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/ComodRivadavia)", code:"America/Argentina/ComodRivadavia"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Cordoba)", code:"America/Argentina/Cordoba"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Jujuy)", code:"America/Argentina/Jujuy"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/La_Rioja)", code:"America/Argentina/La_Rioja"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Mendoza)", code:"America/Argentina/Mendoza"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Rio_Gallegos)", code:"America/Argentina/Rio_Gallegos"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Salta)", code:"America/Argentina/Salta"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/San_Juan)", code:"America/Argentina/San_Juan"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/San_Luis)", code:"America/Argentina/San_Luis"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Tucuman)", code:"America/Argentina/Tucuman"},
{name:"(GMT-3:00) Argentine Time (America/Argentina/Ushuaia)", code:"America/Argentina/Ushuaia"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Aruba)", code:"America/Aruba"},
{name:"(GMT-4:00) Paraguay Time (America/Asuncion)", code:"America/Asuncion"},
{name:"(GMT-5:00) Eastern Standard Time (America/Atikokan)", code:"America/Atikokan"},
{name:"(GMT-10:00) Hawaii-Aleutian Standard Time (America/Atka)", code:"America/Atka"},
{name:"(GMT-3:00) Brasilia Time (America/Bahia)", code:"America/Bahia"},
{name:"(GMT-6:00) Central Standard Time (America/Bahia_Banderas)", code:"America/Bahia_Banderas"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Barbados)", code:"America/Barbados"},
{name:"(GMT-3:00) Brasilia Time (America/Belem)", code:"America/Belem"},
{name:"(GMT-6:00) Central Standard Time (America/Belize)", code:"America/Belize"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Blanc-Sablon)", code:"America/Blanc-Sablon"},
{name:"(GMT-4:00) Amazon Time (America/Boa_Vista)", code:"America/Boa_Vista"},
{name:"(GMT-5:00) Colombia Time (America/Bogota)", code:"America/Bogota"},
{name:"(GMT-7:00) Mountain Standard Time (America/Boise)", code:"America/Boise"},
{name:"(GMT-3:00) Argentine Time (America/Buenos_Aires)", code:"America/Buenos_Aires"},
{name:"(GMT-7:00) Mountain Standard Time (America/Cambridge_Bay)", code:"America/Cambridge_Bay"},
{name:"(GMT-4:00) Amazon Time (America/Campo_Grande)", code:"America/Campo_Grande"},
{name:"(GMT-6:00) Central Standard Time (America/Cancun)", code:"America/Cancun"},
{name:"(GMT-4:30) Venezuela Time (America/Caracas)", code:"America/Caracas"},
{name:"(GMT-3:00) Argentine Time (America/Catamarca)", code:"America/Catamarca"},
{name:"(GMT-3:00) French Guiana Time (America/Cayenne)", code:"America/Cayenne"},
{name:"(GMT-5:00) Eastern Standard Time (America/Cayman)", code:"America/Cayman"},
{name:"(GMT-6:00) Central Standard Time (America/Chicago)", code:"America/Chicago"},
{name:"(GMT-7:00) Mountain Standard Time (America/Chihuahua)", code:"America/Chihuahua"},
{name:"(GMT-5:00) Eastern Standard Time (America/Coral_Harbour)", code:"America/Coral_Harbour"},
{name:"(GMT-3:00) Argentine Time (America/Cordoba)", code:"America/Cordoba"},
{name:"(GMT-6:00) Central Standard Time (America/Costa_Rica)", code:"America/Costa_Rica"},
{name:"(GMT-7:00) Mountain Standard Time (America/Creston)", code:"America/Creston"},
{name:"(GMT-4:00) Amazon Time (America/Cuiaba)", code:"America/Cuiaba"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Curacao)", code:"America/Curacao"},
{name:"(GMT0:00) Greenwich Mean Time (America/Danmarkshavn)", code:"America/Danmarkshavn"},
{name:"(GMT-8:00) Pacific Standard Time (America/Dawson)", code:"America/Dawson"},
{name:"(GMT-7:00) Mountain Standard Time (America/Dawson_Creek)", code:"America/Dawson_Creek"},
{name:"(GMT-7:00) Mountain Standard Time (America/Denver)", code:"America/Denver"},
{name:"(GMT-5:00) Eastern Standard Time (America/Detroit)", code:"America/Detroit"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Dominica)", code:"America/Dominica"},
{name:"(GMT-7:00) Mountain Standard Time (America/Edmonton)", code:"America/Edmonton"},
{name:"(GMT-5:00) Acre Time (America/Eirunepe)", code:"America/Eirunepe"},
{name:"(GMT-6:00) Central Standard Time (America/El_Salvador)", code:"America/El_Salvador"},
{name:"(GMT-8:00) Pacific Standard Time (America/Ensenada)", code:"America/Ensenada"},
{name:"(GMT-5:00) Eastern Standard Time (America/Fort_Wayne)", code:"America/Fort_Wayne"},
{name:"(GMT-3:00) Brasilia Time (America/Fortaleza)", code:"America/Fortaleza"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Glace_Bay)", code:"America/Glace_Bay"},
{name:"(GMT-3:00) Western Greenland Time (America/Godthab)", code:"America/Godthab"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Goose_Bay)", code:"America/Goose_Bay"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Grand_Turk)", code:"America/Grand_Turk"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Grenada)", code:"America/Grenada"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Guadeloupe)", code:"America/Guadeloupe"},
{name:"(GMT-6:00) Central Standard Time (America/Guatemala)", code:"America/Guatemala"},
{name:"(GMT-5:00) Ecuador Time (America/Guayaquil)", code:"America/Guayaquil"},
{name:"(GMT-4:00) Guyana Time (America/Guyana)", code:"America/Guyana"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Halifax)", code:"America/Halifax"},
{name:"(GMT-5:00) Cuba Standard Time (America/Havana)", code:"America/Havana"},
{name:"(GMT-7:00) Mountain Standard Time (America/Hermosillo)", code:"America/Hermosillo"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indiana/Indianapolis)", code:"America/Indiana/Indianapolis"},
{name:"(GMT-6:00) Central Standard Time (America/Indiana/Knox)", code:"America/Indiana/Knox"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indiana/Marengo)", code:"America/Indiana/Marengo"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indiana/Petersburg)", code:"America/Indiana/Petersburg"},
{name:"(GMT-6:00) Central Standard Time (America/Indiana/Tell_City)", code:"America/Indiana/Tell_City"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indiana/Vevay)", code:"America/Indiana/Vevay"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indiana/Vincennes)", code:"America/Indiana/Vincennes"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indiana/Winamac)", code:"America/Indiana/Winamac"},
{name:"(GMT-5:00) Eastern Standard Time (America/Indianapolis)", code:"America/Indianapolis"},
{name:"(GMT-7:00) Mountain Standard Time (America/Inuvik)", code:"America/Inuvik"},
{name:"(GMT-5:00) Eastern Standard Time (America/Iqaluit)", code:"America/Iqaluit"},
{name:"(GMT-5:00) Eastern Standard Time (America/Jamaica)", code:"America/Jamaica"},
{name:"(GMT-3:00) Argentine Time (America/Jujuy)", code:"America/Jujuy"},
{name:"(GMT-9:00) Alaska Standard Time (America/Juneau)", code:"America/Juneau"},
{name:"(GMT-5:00) Eastern Standard Time (America/Kentucky/Louisville)", code:"America/Kentucky/Louisville"},
{name:"(GMT-5:00) Eastern Standard Time (America/Kentucky/Monticello)", code:"America/Kentucky/Monticello"},
{name:"(GMT-6:00) Central Standard Time (America/Knox_IN)", code:"America/Knox_IN"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Kralendijk)", code:"America/Kralendijk"},
{name:"(GMT-4:00) Bolivia Time (America/La_Paz)", code:"America/La_Paz"},
{name:"(GMT-5:00) Peru Time (America/Lima)", code:"America/Lima"},
{name:"(GMT-8:00) Pacific Standard Time (America/Los_Angeles)", code:"America/Los_Angeles"},
{name:"(GMT-5:00) Eastern Standard Time (America/Louisville)", code:"America/Louisville"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Lower_Princes)", code:"America/Lower_Princes"},
{name:"(GMT-3:00) Brasilia Time (America/Maceio)", code:"America/Maceio"},
{name:"(GMT-6:00) Central Standard Time (America/Managua)", code:"America/Managua"},
{name:"(GMT-4:00) Amazon Time (America/Manaus)", code:"America/Manaus"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Marigot)", code:"America/Marigot"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Martinique)", code:"America/Martinique"},
{name:"(GMT-6:00) Central Standard Time (America/Matamoros)", code:"America/Matamoros"},
{name:"(GMT-7:00) Mountain Standard Time (America/Mazatlan)", code:"America/Mazatlan"},
{name:"(GMT-3:00) Argentine Time (America/Mendoza)", code:"America/Mendoza"},
{name:"(GMT-6:00) Central Standard Time (America/Menominee)", code:"America/Menominee"},
{name:"(GMT-6:00) Central Standard Time (America/Merida)", code:"America/Merida"},
{name:"(GMT-8:00) Pacific Standard Time (America/Metlakatla)", code:"America/Metlakatla"},
{name:"(GMT-6:00) Central Standard Time (America/Mexico_City)", code:"America/Mexico_City"},
{name:"(GMT-3:00) Pierre & Miquelon Standard Time (America/Miquelon)", code:"America/Miquelon"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Moncton)", code:"America/Moncton"},
{name:"(GMT-6:00) Central Standard Time (America/Monterrey)", code:"America/Monterrey"},
{name:"(GMT-3:00) Uruguay Time (America/Montevideo)", code:"America/Montevideo"},
{name:"(GMT-5:00) Eastern Standard Time (America/Montreal)", code:"America/Montreal"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Montserrat)", code:"America/Montserrat"},
{name:"(GMT-5:00) Eastern Standard Time (America/Nassau)", code:"America/Nassau"},
{name:"(GMT-5:00) Eastern Standard Time (America/New_York)", code:"America/New_York"},
{name:"(GMT-5:00) Eastern Standard Time (America/Nipigon)", code:"America/Nipigon"},
{name:"(GMT-9:00) Alaska Standard Time (America/Nome)", code:"America/Nome"},
{name:"(GMT-2:00) Fernando de Noronha Time (America/Noronha)", code:"America/Noronha"},
{name:"(GMT-6:00) Central Standard Time (America/North_Dakota/Beulah)", code:"America/North_Dakota/Beulah"},
{name:"(GMT-6:00) Central Standard Time (America/North_Dakota/Center)", code:"America/North_Dakota/Center"},
{name:"(GMT-6:00) Central Standard Time (America/North_Dakota/New_Salem)", code:"America/North_Dakota/New_Salem"},
{name:"(GMT-7:00) Mountain Standard Time (America/Ojinaga)", code:"America/Ojinaga"},
{name:"(GMT-5:00) Eastern Standard Time (America/Panama)", code:"America/Panama"},
{name:"(GMT-5:00) Eastern Standard Time (America/Pangnirtung)", code:"America/Pangnirtung"},
{name:"(GMT-3:00) Suriname Time (America/Paramaribo)", code:"America/Paramaribo"},
{name:"(GMT-7:00) Mountain Standard Time (America/Phoenix)", code:"America/Phoenix"},
{name:"(GMT-5:00) Eastern Standard Time (America/Port-au-Prince)", code:"America/Port-au-Prince"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Port_of_Spain)", code:"America/Port_of_Spain"},
{name:"(GMT-5:00) Acre Time (America/Porto_Acre)", code:"America/Porto_Acre"},
{name:"(GMT-4:00) Amazon Time (America/Porto_Velho)", code:"America/Porto_Velho"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Puerto_Rico)", code:"America/Puerto_Rico"},
{name:"(GMT-6:00) Central Standard Time (America/Rainy_River)", code:"America/Rainy_River"},
{name:"(GMT-6:00) Central Standard Time (America/Rankin_Inlet)", code:"America/Rankin_Inlet"},
{name:"(GMT-3:00) Brasilia Time (America/Recife)", code:"America/Recife"},
{name:"(GMT-6:00) Central Standard Time (America/Regina)", code:"America/Regina"},
{name:"(GMT-6:00) Central Standard Time (America/Resolute)", code:"America/Resolute"},
{name:"(GMT-5:00) Acre Time (America/Rio_Branco)", code:"America/Rio_Branco"},
{name:"(GMT-3:00) Argentine Time (America/Rosario)", code:"America/Rosario"},
{name:"(GMT-8:00) Pacific Standard Time (America/Santa_Isabel)", code:"America/Santa_Isabel"},
{name:"(GMT-3:00) Brasilia Time (America/Santarem)", code:"America/Santarem"},
{name:"(GMT-4:00) Chile Time (America/Santiago)", code:"America/Santiago"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Santo_Domingo)", code:"America/Santo_Domingo"},
{name:"(GMT-3:00) Brasilia Time (America/Sao_Paulo)", code:"America/Sao_Paulo"},
{name:"(GMT-1:00) Eastern Greenland Time (America/Scoresbysund)", code:"America/Scoresbysund"},
{name:"(GMT-7:00) Mountain Standard Time (America/Shiprock)", code:"America/Shiprock"},
{name:"(GMT-9:00) Alaska Standard Time (America/Sitka)", code:"America/Sitka"},
{name:"(GMT-4:00) Atlantic Standard Time (America/St_Barthelemy)", code:"America/St_Barthelemy"},
{name:"(GMT-3:30) Newfoundland Standard Time (America/St_Johns)", code:"America/St_Johns"},
{name:"(GMT-4:00) Atlantic Standard Time (America/St_Kitts)", code:"America/St_Kitts"},
{name:"(GMT-4:00) Atlantic Standard Time (America/St_Lucia)", code:"America/St_Lucia"},
{name:"(GMT-4:00) Atlantic Standard Time (America/St_Thomas)", code:"America/St_Thomas"},
{name:"(GMT-4:00) Atlantic Standard Time (America/St_Vincent)", code:"America/St_Vincent"},
{name:"(GMT-6:00) Central Standard Time (America/Swift_Current)", code:"America/Swift_Current"},
{name:"(GMT-6:00) Central Standard Time (America/Tegucigalpa)", code:"America/Tegucigalpa"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Thule)", code:"America/Thule"},
{name:"(GMT-5:00) Eastern Standard Time (America/Thunder_Bay)", code:"America/Thunder_Bay"},
{name:"(GMT-8:00) Pacific Standard Time (America/Tijuana)", code:"America/Tijuana"},
{name:"(GMT-5:00) Eastern Standard Time (America/Toronto)", code:"America/Toronto"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Tortola)", code:"America/Tortola"},
{name:"(GMT-8:00) Pacific Standard Time (America/Vancouver)", code:"America/Vancouver"},
{name:"(GMT-4:00) Atlantic Standard Time (America/Virgin)", code:"America/Virgin"},
{name:"(GMT-8:00) Pacific Standard Time (America/Whitehorse)", code:"America/Whitehorse"},
{name:"(GMT-6:00) Central Standard Time (America/Winnipeg)", code:"America/Winnipeg"},
{name:"(GMT-9:00) Alaska Standard Time (America/Yakutat)", code:"America/Yakutat"},
{name:"(GMT-7:00) Mountain Standard Time (America/Yellowknife)", code:"America/Yellowknife"},
{name:"(GMT+8:00) Australian Western Standard Time (Antarctica/Casey)", code:"Antarctica/Casey"},
{name:"(GMT+7:00) Davis Time (Antarctica/Davis)", code:"Antarctica/Davis"},
{name:"(GMT+10:00) Dumont-d'Urville Time (Antarctica/DumontDUrville)", code:"Antarctica/DumontDUrville"},
{name:"(GMT+11:00) Macquarie Island Standard Time (Antarctica/Macquarie)", code:"Antarctica/Macquarie"},
{name:"(GMT+5:00) Mawson Time (Antarctica/Mawson)", code:"Antarctica/Mawson"},
{name:"(GMT+12:00) New Zealand Standard Time (Antarctica/McMurdo)", code:"Antarctica/McMurdo"},
{name:"(GMT-4:00) Chile Time (Antarctica/Palmer)", code:"Antarctica/Palmer"},
{name:"(GMT-3:00) Rothera Time (Antarctica/Rothera)", code:"Antarctica/Rothera"},
{name:"(GMT+12:00) New Zealand Standard Time (Antarctica/South_Pole)", code:"Antarctica/South_Pole"},
{name:"(GMT+3:00) Syowa Time (Antarctica/Syowa)", code:"Antarctica/Syowa"},
{name:"(GMT0:00) Coordinated Universal Time (Antarctica/Troll)", code:"Antarctica/Troll"},
{name:"(GMT+6:00) Vostok Time (Antarctica/Vostok)", code:"Antarctica/Vostok"},
{name:"(GMT+1:00) Central European Time (Arctic/Longyearbyen)", code:"Arctic/Longyearbyen"},
{name:"(GMT+3:00) Arabia Standard Time (Asia/Aden)", code:"Asia/Aden"},
{name:"(GMT+6:00) Alma-Ata Time (Asia/Almaty)", code:"Asia/Almaty"},
{name:"(GMT+2:00) Eastern European Time (Asia/Amman)", code:"Asia/Amman"},
{name:"(GMT+12:00) Anadyr Time (Asia/Anadyr)", code:"Asia/Anadyr"},
{name:"(GMT+5:00) Aqtau Time (Asia/Aqtau)", code:"Asia/Aqtau"},
{name:"(GMT+5:00) Aqtobe Time (Asia/Aqtobe)", code:"Asia/Aqtobe"},
{name:"(GMT+5:00) Turkmenistan Time (Asia/Ashgabat)", code:"Asia/Ashgabat"},
{name:"(GMT+5:00) Turkmenistan Time (Asia/Ashkhabad)", code:"Asia/Ashkhabad"},
{name:"(GMT+3:00) Arabia Standard Time (Asia/Baghdad)", code:"Asia/Baghdad"},
{name:"(GMT+3:00) Arabia Standard Time (Asia/Bahrain)", code:"Asia/Bahrain"},
{name:"(GMT+4:00) Azerbaijan Time (Asia/Baku)", code:"Asia/Baku"},
{name:"(GMT+7:00) Indochina Time (Asia/Bangkok)", code:"Asia/Bangkok"},
{name:"(GMT+2:00) Eastern European Time (Asia/Beirut)", code:"Asia/Beirut"},
{name:"(GMT+6:00) Kirgizstan Time (Asia/Bishkek)", code:"Asia/Bishkek"},
{name:"(GMT+8:00) Brunei Time (Asia/Brunei)", code:"Asia/Brunei"},
{name:"(GMT+5:30) India Standard Time (Asia/Calcutta)", code:"Asia/Calcutta"},
{name:"(GMT+8:00) Irkutsk Time (Asia/Chita)", code:"Asia/Chita"},
{name:"(GMT+8:00) Choibalsan Time (Asia/Choibalsan)", code:"Asia/Choibalsan"},
{name:"(GMT+8:00) China Standard Time (Asia/Chongqing)", code:"Asia/Chongqing"},
{name:"(GMT+8:00) China Standard Time (Asia/Chungking)", code:"Asia/Chungking"},
{name:"(GMT+5:30) India Standard Time (Asia/Colombo)", code:"Asia/Colombo"},
{name:"(GMT+6:00) Bangladesh Time (Asia/Dacca)", code:"Asia/Dacca"},
{name:"(GMT+2:00) Eastern European Time (Asia/Damascus)", code:"Asia/Damascus"},
{name:"(GMT+6:00) Bangladesh Time (Asia/Dhaka)", code:"Asia/Dhaka"},
{name:"(GMT+9:00) Timor-Leste Time (Asia/Dili)", code:"Asia/Dili"},
{name:"(GMT+4:00) Gulf Standard Time (Asia/Dubai)", code:"Asia/Dubai"},
{name:"(GMT+5:00) Tajikistan Time (Asia/Dushanbe)", code:"Asia/Dushanbe"},
{name:"(GMT+2:00) Eastern European Time (Asia/Gaza)", code:"Asia/Gaza"},
{name:"(GMT+8:00) China Standard Time (Asia/Harbin)", code:"Asia/Harbin"},
{name:"(GMT+2:00) Eastern European Time (Asia/Hebron)", code:"Asia/Hebron"},
{name:"(GMT+7:00) Indochina Time (Asia/Ho_Chi_Minh)", code:"Asia/Ho_Chi_Minh"},
{name:"(GMT+8:00) Hong Kong Time (Asia/Hong_Kong)", code:"Asia/Hong_Kong"},
{name:"(GMT+7:00) Hovd Time (Asia/Hovd)", code:"Asia/Hovd"},
{name:"(GMT+8:00) Irkutsk Time (Asia/Irkutsk)", code:"Asia/Irkutsk"},
{name:"(GMT+2:00) Eastern European Time (Asia/Istanbul)", code:"Asia/Istanbul"},
{name:"(GMT+7:00) West Indonesia Time (Asia/Jakarta)", code:"Asia/Jakarta"},
{name:"(GMT+9:00) East Indonesia Time (Asia/Jayapura)", code:"Asia/Jayapura"},
{name:"(GMT+2:00) Israel Standard Time (Asia/Jerusalem)", code:"Asia/Jerusalem"},
{name:"(GMT+4:30) Afghanistan Time (Asia/Kabul)", code:"Asia/Kabul"},
{name:"(GMT+12:00) Petropavlovsk-Kamchatski Time (Asia/Kamchatka)", code:"Asia/Kamchatka"},
{name:"(GMT+5:00) Pakistan Time (Asia/Karachi)", code:"Asia/Karachi"},
{name:"(GMT+6:00) Xinjiang Standard Time (Asia/Kashgar)", code:"Asia/Kashgar"},
{name:"(GMT+5:45) Nepal Time (Asia/Kathmandu)", code:"Asia/Kathmandu"},
{name:"(GMT+5:45) Nepal Time (Asia/Katmandu)", code:"Asia/Katmandu"},
{name:"(GMT+9:00) Khandyga Time (Asia/Khandyga)", code:"Asia/Khandyga"},
{name:"(GMT+5:30) India Standard Time (Asia/Kolkata)", code:"Asia/Kolkata"},
{name:"(GMT+7:00) Krasnoyarsk Time (Asia/Krasnoyarsk)", code:"Asia/Krasnoyarsk"},
{name:"(GMT+8:00) Malaysia Time (Asia/Kuala_Lumpur)", code:"Asia/Kuala_Lumpur"},
{name:"(GMT+8:00) Malaysia Time (Asia/Kuching)", code:"Asia/Kuching"},
{name:"(GMT+3:00) Arabia Standard Time (Asia/Kuwait)", code:"Asia/Kuwait"},
{name:"(GMT+8:00) China Standard Time (Asia/Macao)", code:"Asia/Macao"},
{name:"(GMT+8:00) China Standard Time (Asia/Macau)", code:"Asia/Macau"},
{name:"(GMT+10:00) Magadan Time (Asia/Magadan)", code:"Asia/Magadan"},
{name:"(GMT+8:00) Central Indonesia Time (Asia/Makassar)", code:"Asia/Makassar"},
{name:"(GMT+8:00) Philippines Time (Asia/Manila)", code:"Asia/Manila"},
{name:"(GMT+4:00) Gulf Standard Time (Asia/Muscat)", code:"Asia/Muscat"},
{name:"(GMT+2:00) Eastern European Time (Asia/Nicosia)", code:"Asia/Nicosia"},
{name:"(GMT+7:00) Krasnoyarsk Time (Asia/Novokuznetsk)", code:"Asia/Novokuznetsk"},
{name:"(GMT+6:00) Novosibirsk Time (Asia/Novosibirsk)", code:"Asia/Novosibirsk"},
{name:"(GMT+6:00) Omsk Time (Asia/Omsk)", code:"Asia/Omsk"},
{name:"(GMT+5:00) Oral Time (Asia/Oral)", code:"Asia/Oral"},
{name:"(GMT+7:00) Indochina Time (Asia/Phnom_Penh)", code:"Asia/Phnom_Penh"},
{name:"(GMT+7:00) West Indonesia Time (Asia/Pontianak)", code:"Asia/Pontianak"},
{name:"(GMT+9:00) Korea Standard Time (Asia/Pyongyang)", code:"Asia/Pyongyang"},
{name:"(GMT+3:00) Arabia Standard Time (Asia/Qatar)", code:"Asia/Qatar"},
{name:"(GMT+6:00) Qyzylorda Time (Asia/Qyzylorda)", code:"Asia/Qyzylorda"},
{name:"(GMT+6:30) Myanmar Time (Asia/Rangoon)", code:"Asia/Rangoon"},
{name:"(GMT+3:00) Arabia Standard Time (Asia/Riyadh)", code:"Asia/Riyadh"},
{name:"(GMT+7:00) Indochina Time (Asia/Saigon)", code:"Asia/Saigon"},
{name:"(GMT+10:00) Sakhalin Time (Asia/Sakhalin)", code:"Asia/Sakhalin"},
{name:"(GMT+5:00) Uzbekistan Time (Asia/Samarkand)", code:"Asia/Samarkand"},
{name:"(GMT+9:00) Korea Standard Time (Asia/Seoul)", code:"Asia/Seoul"},
{name:"(GMT+8:00) China Standard Time (Asia/Shanghai)", code:"Asia/Shanghai"},
{name:"(GMT+8:00) Singapore Time (Asia/Singapore)", code:"Asia/Singapore"},
{name:"(GMT+11:00) Srednekolymsk Time (Asia/Srednekolymsk)", code:"Asia/Srednekolymsk"},
{name:"(GMT+8:00) China Standard Time (Asia/Taipei)", code:"Asia/Taipei"},
{name:"(GMT+5:00) Uzbekistan Time (Asia/Tashkent)", code:"Asia/Tashkent"},
{name:"(GMT+4:00) Georgia Time (Asia/Tbilisi)", code:"Asia/Tbilisi"},
{name:"(GMT+3:30) Iran Standard Time (Asia/Tehran)", code:"Asia/Tehran"},
{name:"(GMT+2:00) Israel Standard Time (Asia/Tel_Aviv)", code:"Asia/Tel_Aviv"},
{name:"(GMT+6:00) Bhutan Time (Asia/Thimbu)", code:"Asia/Thimbu"},
{name:"(GMT+6:00) Bhutan Time (Asia/Thimphu)", code:"Asia/Thimphu"},
{name:"(GMT+9:00) Japan Standard Time (Asia/Tokyo)", code:"Asia/Tokyo"},
{name:"(GMT+8:00) Central Indonesia Time (Asia/Ujung_Pandang)", code:"Asia/Ujung_Pandang"},
{name:"(GMT+8:00) Ulaanbaatar Time (Asia/Ulaanbaatar)", code:"Asia/Ulaanbaatar"},
{name:"(GMT+8:00) Ulaanbaatar Time (Asia/Ulan_Bator)", code:"Asia/Ulan_Bator"},
{name:"(GMT+6:00) Xinjiang Standard Time (Asia/Urumqi)", code:"Asia/Urumqi"},
{name:"(GMT+10:00) Ust-Nera Time (Asia/Ust-Nera)", code:"Asia/Ust-Nera"},
{name:"(GMT+7:00) Indochina Time (Asia/Vientiane)", code:"Asia/Vientiane"},
{name:"(GMT+10:00) Vladivostok Time (Asia/Vladivostok)", code:"Asia/Vladivostok"},
{name:"(GMT+9:00) Yakutsk Time (Asia/Yakutsk)", code:"Asia/Yakutsk"},
{name:"(GMT+5:00) Yekaterinburg Time (Asia/Yekaterinburg)", code:"Asia/Yekaterinburg"},
{name:"(GMT+4:00) Armenia Time (Asia/Yerevan)", code:"Asia/Yerevan"},
{name:"(GMT-1:00) Azores Time (Atlantic/Azores)", code:"Atlantic/Azores"},
{name:"(GMT-4:00) Atlantic Standard Time (Atlantic/Bermuda)", code:"Atlantic/Bermuda"},
{name:"(GMT0:00) Western European Time (Atlantic/Canary)", code:"Atlantic/Canary"},
{name:"(GMT-1:00) Cape Verde Time (Atlantic/Cape_Verde)", code:"Atlantic/Cape_Verde"},
{name:"(GMT0:00) Western European Time (Atlantic/Faeroe)", code:"Atlantic/Faeroe"},
{name:"(GMT0:00) Western European Time (Atlantic/Faroe)", code:"Atlantic/Faroe"},
{name:"(GMT+1:00) Central European Time (Atlantic/Jan_Mayen)", code:"Atlantic/Jan_Mayen"},
{name:"(GMT0:00) Western European Time (Atlantic/Madeira)", code:"Atlantic/Madeira"},
{name:"(GMT0:00) Greenwich Mean Time (Atlantic/Reykjavik)", code:"Atlantic/Reykjavik"},
{name:"(GMT-2:00) South Georgia Standard Time (Atlantic/South_Georgia)", code:"Atlantic/South_Georgia"},
{name:"(GMT0:00) Greenwich Mean Time (Atlantic/St_Helena)", code:"Atlantic/St_Helena"},
{name:"(GMT-3:00) Falkland Is. Time (Atlantic/Stanley)", code:"Atlantic/Stanley"},
{name:"(GMT+10:00) Australian Eastern Standard Time (New South Wales) (Australia/ACT)", code:"Australia/ACT"},
{name:"(GMT+9:30) Australian Central Standard Time (South Australia) (Australia/Adelaide)", code:"Australia/Adelaide"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Queensland) (Australia/Brisbane)", code:"Australia/Brisbane"},
{name:"(GMT+9:30) Australian Central Standard Time (South Australia/New South Wales) (Australia/Broken_Hill)", code:"Australia/Broken_Hill"},
{name:"(GMT+10:00) Australian Eastern Standard Time (New South Wales) (Australia/Canberra)", code:"Australia/Canberra"},
{name:"(GMT+10:00) Australian Eastern Standard Time (New South Wales) (Australia/Currie)", code:"Australia/Currie"},
{name:"(GMT+9:30) Australian Central Standard Time (Northern Territory) (Australia/Darwin)", code:"Australia/Darwin"},
{name:"(GMT+8:45) Australian Central Western Standard Time (Australia/Eucla)", code:"Australia/Eucla"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Tasmania) (Australia/Hobart)", code:"Australia/Hobart"},
{name:"(GMT+10:30) Lord Howe Standard Time (Australia/LHI)", code:"Australia/LHI"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Queensland) (Australia/Lindeman)", code:"Australia/Lindeman"},
{name:"(GMT+10:30) Lord Howe Standard Time (Australia/Lord_Howe)", code:"Australia/Lord_Howe"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Victoria) (Australia/Melbourne)", code:"Australia/Melbourne"},
{name:"(GMT+10:00) Australian Eastern Standard Time (New South Wales) (Australia/NSW)", code:"Australia/NSW"},
{name:"(GMT+9:30) Australian Central Standard Time (Northern Territory) (Australia/North)", code:"Australia/North"},
{name:"(GMT+8:00) Australian Western Standard Time (Australia/Perth)", code:"Australia/Perth"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Queensland) (Australia/Queensland)", code:"Australia/Queensland"},
{name:"(GMT+9:30) Australian Central Standard Time (South Australia) (Australia/South)", code:"Australia/South"},
{name:"(GMT+10:00) Australian Eastern Standard Time (New South Wales) (Australia/Sydney)", code:"Australia/Sydney"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Tasmania) (Australia/Tasmania)", code:"Australia/Tasmania"},
{name:"(GMT+10:00) Australian Eastern Standard Time (Victoria) (Australia/Victoria)", code:"Australia/Victoria"},
{name:"(GMT+8:00) Australian Western Standard Time (Australia/West)", code:"Australia/West"},
{name:"(GMT+9:30) Australian Central Standard Time (South Australia/New South Wales) (Australia/Yancowinna)", code:"Australia/Yancowinna"},
{name:"(GMT-5:00) Acre Time (Brazil/Acre)", code:"Brazil/Acre"},
{name:"(GMT-2:00) Fernando de Noronha Time (Brazil/DeNoronha)", code:"Brazil/DeNoronha"},
{name:"(GMT-3:00) Brasilia Time (Brazil/East)", code:"Brazil/East"},
{name:"(GMT-4:00) Amazon Time (Brazil/West)", code:"Brazil/West"},
{name:"(GMT+1:00) Central European Time (CET)", code:"CET"},
{name:"(GMT-6:00) Central Standard Time (CST6CDT)", code:"CST6CDT"},
{name:"(GMT-4:00) Atlantic Standard Time (Canada/Atlantic)", code:"Canada/Atlantic"},
{name:"(GMT-6:00) Central Standard Time (Canada/Central)", code:"Canada/Central"},
{name:"(GMT-6:00) Central Standard Time (Canada/East-Saskatchewan)", code:"Canada/East-Saskatchewan"},
{name:"(GMT-5:00) Eastern Standard Time (Canada/Eastern)", code:"Canada/Eastern"},
{name:"(GMT-7:00) Mountain Standard Time (Canada/Mountain)", code:"Canada/Mountain"},
{name:"(GMT-3:30) Newfoundland Standard Time (Canada/Newfoundland)", code:"Canada/Newfoundland"},
{name:"(GMT-8:00) Pacific Standard Time (Canada/Pacific)", code:"Canada/Pacific"},
{name:"(GMT-6:00) Central Standard Time (Canada/Saskatchewan)", code:"Canada/Saskatchewan"},
{name:"(GMT-8:00) Pacific Standard Time (Canada/Yukon)", code:"Canada/Yukon"},
{name:"(GMT-4:00) Chile Time (Chile/Continental)", code:"Chile/Continental"},
{name:"(GMT-6:00) Easter Is. Time (Chile/EasterIsland)", code:"Chile/EasterIsland"},
{name:"(GMT-5:00) Cuba Standard Time (Cuba)", code:"Cuba"},
{name:"(GMT+2:00) Eastern European Time (EET)", code:"EET"},
{name:"(GMT-5:00) Eastern Standard Time (EST5EDT)", code:"EST5EDT"},
{name:"(GMT+2:00) Eastern European Time (Egypt)", code:"Egypt"},
{name:"(GMT0:00) Greenwich Mean Time (Eire)", code:"Eire"},
{name:"(GMT0:00) Greenwich Mean Time (Etc/GMT)", code:"Etc/GMT"},
{name:"(GMT0:00) Greenwich Mean Time (Etc/GMT+0)", code:"Etc/GMT+0"},
{name:"(GMT-1:00) GMT-01:00 (Etc/GMT+1)", code:"Etc/GMT+1"},
{name:"(GMT-10:00) GMT-10:00 (Etc/GMT+10)", code:"Etc/GMT+10"},
{name:"(GMT-11:00) GMT-11:00 (Etc/GMT+11)", code:"Etc/GMT+11"},
{name:"(GMT-12:00) GMT-12:00 (Etc/GMT+12)", code:"Etc/GMT+12"},
{name:"(GMT-2:00) GMT-02:00 (Etc/GMT+2)", code:"Etc/GMT+2"},
{name:"(GMT-3:00) GMT-03:00 (Etc/GMT+3)", code:"Etc/GMT+3"},
{name:"(GMT-4:00) GMT-04:00 (Etc/GMT+4)", code:"Etc/GMT+4"},
{name:"(GMT-5:00) GMT-05:00 (Etc/GMT+5)", code:"Etc/GMT+5"},
{name:"(GMT-6:00) GMT-06:00 (Etc/GMT+6)", code:"Etc/GMT+6"},
{name:"(GMT-7:00) GMT-07:00 (Etc/GMT+7)", code:"Etc/GMT+7"},
{name:"(GMT-8:00) GMT-08:00 (Etc/GMT+8)", code:"Etc/GMT+8"},
{name:"(GMT-9:00) GMT-09:00 (Etc/GMT+9)", code:"Etc/GMT+9"},
{name:"(GMT0:00) Greenwich Mean Time (Etc/GMT-0)", code:"Etc/GMT-0"},
{name:"(GMT+1:00) GMT+01:00 (Etc/GMT-1)", code:"Etc/GMT-1"},
{name:"(GMT+10:00) GMT+10:00 (Etc/GMT-10)", code:"Etc/GMT-10"},
{name:"(GMT+11:00) GMT+11:00 (Etc/GMT-11)", code:"Etc/GMT-11"},
{name:"(GMT+12:00) GMT+12:00 (Etc/GMT-12)", code:"Etc/GMT-12"},
{name:"(GMT+13:00) GMT+13:00 (Etc/GMT-13)", code:"Etc/GMT-13"},
{name:"(GMT+14:00) GMT+14:00 (Etc/GMT-14)", code:"Etc/GMT-14"},
{name:"(GMT+2:00) GMT+02:00 (Etc/GMT-2)", code:"Etc/GMT-2"},
{name:"(GMT+3:00) GMT+03:00 (Etc/GMT-3)", code:"Etc/GMT-3"},
{name:"(GMT+4:00) GMT+04:00 (Etc/GMT-4)", code:"Etc/GMT-4"},
{name:"(GMT+5:00) GMT+05:00 (Etc/GMT-5)", code:"Etc/GMT-5"},
{name:"(GMT+6:00) GMT+06:00 (Etc/GMT-6)", code:"Etc/GMT-6"},
{name:"(GMT+7:00) GMT+07:00 (Etc/GMT-7)", code:"Etc/GMT-7"},
{name:"(GMT+8:00) GMT+08:00 (Etc/GMT-8)", code:"Etc/GMT-8"},
{name:"(GMT+9:00) GMT+09:00 (Etc/GMT-9)", code:"Etc/GMT-9"},
{name:"(GMT0:00) Greenwich Mean Time (Etc/GMT0)", code:"Etc/GMT0"},
{name:"(GMT0:00) Greenwich Mean Time (Etc/Greenwich)", code:"Etc/Greenwich"},
{name:"(GMT0:00) Coordinated Universal Time (Etc/UCT)", code:"Etc/UCT"},
{name:"(GMT0:00) Coordinated Universal Time (Etc/UTC)", code:"Etc/UTC"},
{name:"(GMT0:00) Coordinated Universal Time (Etc/Universal)", code:"Etc/Universal"},
{name:"(GMT0:00) Coordinated Universal Time (Etc/Zulu)", code:"Etc/Zulu"},
{name:"(GMT+1:00) Central European Time (Europe/Amsterdam)", code:"Europe/Amsterdam"},
{name:"(GMT+1:00) Central European Time (Europe/Andorra)", code:"Europe/Andorra"},
{name:"(GMT+2:00) Eastern European Time (Europe/Athens)", code:"Europe/Athens"},
{name:"(GMT0:00) Greenwich Mean Time (Europe/Belfast)", code:"Europe/Belfast"},
{name:"(GMT+1:00) Central European Time (Europe/Belgrade)", code:"Europe/Belgrade"},
{name:"(GMT+1:00) Central European Time (Europe/Berlin)", code:"Europe/Berlin"},
{name:"(GMT+1:00) Central European Time (Europe/Bratislava)", code:"Europe/Bratislava"},
{name:"(GMT+1:00) Central European Time (Europe/Brussels)", code:"Europe/Brussels"},
{name:"(GMT+2:00) Eastern European Time (Europe/Bucharest)", code:"Europe/Bucharest"},
{name:"(GMT+1:00) Central European Time (Europe/Budapest)", code:"Europe/Budapest"},
{name:"(GMT+1:00) Central European Time (Europe/Busingen)", code:"Europe/Busingen"},
{name:"(GMT+2:00) Eastern European Time (Europe/Chisinau)", code:"Europe/Chisinau"},
{name:"(GMT+1:00) Central European Time (Europe/Copenhagen)", code:"Europe/Copenhagen"},
{name:"(GMT0:00) Greenwich Mean Time (Europe/Dublin)", code:"Europe/Dublin"},
{name:"(GMT+1:00) Central European Time (Europe/Gibraltar)", code:"Europe/Gibraltar"},
{name:"(GMT0:00) Greenwich Mean Time (Europe/Guernsey)", code:"Europe/Guernsey"},
{name:"(GMT+2:00) Eastern European Time (Europe/Helsinki)", code:"Europe/Helsinki"},
{name:"(GMT0:00) Greenwich Mean Time (Europe/Isle_of_Man)", code:"Europe/Isle_of_Man"},
{name:"(GMT+2:00) Eastern European Time (Europe/Istanbul)", code:"Europe/Istanbul"},
{name:"(GMT0:00) Greenwich Mean Time (Europe/Jersey)", code:"Europe/Jersey"},
{name:"(GMT+2:00) Eastern European Time (Europe/Kaliningrad)", code:"Europe/Kaliningrad"},
{name:"(GMT+2:00) Eastern European Time (Europe/Kiev)", code:"Europe/Kiev"},
{name:"(GMT0:00) Western European Time (Europe/Lisbon)", code:"Europe/Lisbon"},
{name:"(GMT+1:00) Central European Time (Europe/Ljubljana)", code:"Europe/Ljubljana"},
{name:"(GMT0:00) Greenwich Mean Time (Europe/London)", code:"Europe/London"},
{name:"(GMT+1:00) Central European Time (Europe/Luxembourg)", code:"Europe/Luxembourg"},
{name:"(GMT+1:00) Central European Time (Europe/Madrid)", code:"Europe/Madrid"},
{name:"(GMT+1:00) Central European Time (Europe/Malta)", code:"Europe/Malta"},
{name:"(GMT+2:00) Eastern European Time (Europe/Mariehamn)", code:"Europe/Mariehamn"},
{name:"(GMT+3:00) Moscow Standard Time (Europe/Minsk)", code:"Europe/Minsk"},
{name:"(GMT+1:00) Central European Time (Europe/Monaco)", code:"Europe/Monaco"},
{name:"(GMT+3:00) Moscow Standard Time (Europe/Moscow)", code:"Europe/Moscow"},
{name:"(GMT+2:00) Eastern European Time (Europe/Nicosia)", code:"Europe/Nicosia"},
{name:"(GMT+1:00) Central European Time (Europe/Oslo)", code:"Europe/Oslo"},
{name:"(GMT+1:00) Central European Time (Europe/Paris)", code:"Europe/Paris"},
{name:"(GMT+1:00) Central European Time (Europe/Podgorica)", code:"Europe/Podgorica"},
{name:"(GMT+1:00) Central European Time (Europe/Prague)", code:"Europe/Prague"},
{name:"(GMT+2:00) Eastern European Time (Europe/Riga)", code:"Europe/Riga"},
{name:"(GMT+1:00) Central European Time (Europe/Rome)", code:"Europe/Rome"},
{name:"(GMT+4:00) Samara Time (Europe/Samara)", code:"Europe/Samara"},
{name:"(GMT+1:00) Central European Time (Europe/San_Marino)", code:"Europe/San_Marino"},
{name:"(GMT+1:00) Central European Time (Europe/Sarajevo)", code:"Europe/Sarajevo"},
{name:"(GMT+3:00) Moscow Standard Time (Europe/Simferopol)", code:"Europe/Simferopol"},
{name:"(GMT+1:00) Central European Time (Europe/Skopje)", code:"Europe/Skopje"},
{name:"(GMT+2:00) Eastern European Time (Europe/Sofia)", code:"Europe/Sofia"},
{name:"(GMT+1:00) Central European Time (Europe/Stockholm)", code:"Europe/Stockholm"},
{name:"(GMT+2:00) Eastern European Time (Europe/Tallinn)", code:"Europe/Tallinn"},
{name:"(GMT+1:00) Central European Time (Europe/Tirane)", code:"Europe/Tirane"},
{name:"(GMT+2:00) Eastern European Time (Europe/Tiraspol)", code:"Europe/Tiraspol"},
{name:"(GMT+2:00) Eastern European Time (Europe/Uzhgorod)", code:"Europe/Uzhgorod"},
{name:"(GMT+1:00) Central European Time (Europe/Vaduz)", code:"Europe/Vaduz"},
{name:"(GMT+1:00) Central European Time (Europe/Vatican)", code:"Europe/Vatican"},
{name:"(GMT+1:00) Central European Time (Europe/Vienna)", code:"Europe/Vienna"},
{name:"(GMT+2:00) Eastern European Time (Europe/Vilnius)", code:"Europe/Vilnius"},
{name:"(GMT+3:00) Moscow Standard Time (Europe/Volgograd)", code:"Europe/Volgograd"},
{name:"(GMT+1:00) Central European Time (Europe/Warsaw)", code:"Europe/Warsaw"},
{name:"(GMT+1:00) Central European Time (Europe/Zagreb)", code:"Europe/Zagreb"},
{name:"(GMT+2:00) Eastern European Time (Europe/Zaporozhye)", code:"Europe/Zaporozhye"},
{name:"(GMT+1:00) Central European Time (Europe/Zurich)", code:"Europe/Zurich"},
{name:"(GMT0:00) Greenwich Mean Time (GB)", code:"GB"},
{name:"(GMT0:00) Greenwich Mean Time (GB-Eire)", code:"GB-Eire"},
{name:"(GMT0:00) Greenwich Mean Time (GMT)", code:"GMT"},
{name:"(GMT0:00) Greenwich Mean Time (GMT0)", code:"GMT0"},
{name:"(GMT0:00) Greenwich Mean Time (Greenwich)", code:"Greenwich"},
{name:"(GMT+8:00) Hong Kong Time (Hongkong)", code:"Hongkong"},
{name:"(GMT0:00) Greenwich Mean Time (Iceland)", code:"Iceland"},
{name:"(GMT+3:00) Eastern African Time (Indian/Antananarivo)", code:"Indian/Antananarivo"},
{name:"(GMT+6:00) Indian Ocean Territory Time (Indian/Chagos)", code:"Indian/Chagos"},
{name:"(GMT+7:00) Christmas Island Time (Indian/Christmas)", code:"Indian/Christmas"},
{name:"(GMT+6:30) Cocos Islands Time (Indian/Cocos)", code:"Indian/Cocos"},
{name:"(GMT+3:00) Eastern African Time (Indian/Comoro)", code:"Indian/Comoro"},
{name:"(GMT+5:00) French Southern & Antarctic Lands Time (Indian/Kerguelen)", code:"Indian/Kerguelen"},
{name:"(GMT+4:00) Seychelles Time (Indian/Mahe)", code:"Indian/Mahe"},
{name:"(GMT+5:00) Maldives Time (Indian/Maldives)", code:"Indian/Maldives"},
{name:"(GMT+4:00) Mauritius Time (Indian/Mauritius)", code:"Indian/Mauritius"},
{name:"(GMT+3:00) Eastern African Time (Indian/Mayotte)", code:"Indian/Mayotte"},
{name:"(GMT+4:00) Reunion Time (Indian/Reunion)", code:"Indian/Reunion"},
{name:"(GMT+3:30) Iran Standard Time (Iran)", code:"Iran"},
{name:"(GMT+2:00) Israel Standard Time (Israel)", code:"Israel"},
{name:"(GMT-5:00) Eastern Standard Time (Jamaica)", code:"Jamaica"},
{name:"(GMT+9:00) Japan Standard Time (Japan)", code:"Japan"},
{name:"(GMT+12:00) Marshall Islands Time (Kwajalein)", code:"Kwajalein"},
{name:"(GMT+2:00) Eastern European Time (Libya)", code:"Libya"},
{name:"(GMT+1:00) Middle Europe Time (MET)", code:"MET"},
{name:"(GMT-7:00) Mountain Standard Time (MST7MDT)", code:"MST7MDT"},
{name:"(GMT-8:00) Pacific Standard Time (Mexico/BajaNorte)", code:"Mexico/BajaNorte"},
{name:"(GMT-7:00) Mountain Standard Time (Mexico/BajaSur)", code:"Mexico/BajaSur"},
{name:"(GMT-6:00) Central Standard Time (Mexico/General)", code:"Mexico/General"},
{name:"(GMT+12:00) New Zealand Standard Time (NZ)", code:"NZ"},
{name:"(GMT+12:45) Chatham Standard Time (NZ-CHAT)", code:"NZ-CHAT"},
{name:"(GMT-7:00) Mountain Standard Time (Navajo)", code:"Navajo"},
{name:"(GMT+8:00) China Standard Time (PRC)", code:"PRC"},
{name:"(GMT-8:00) Pacific Standard Time (PST8PDT)", code:"PST8PDT"},
{name:"(GMT+13:00) West Samoa Standard Time (Pacific/Apia)", code:"Pacific/Apia"},
{name:"(GMT+12:00) New Zealand Standard Time (Pacific/Auckland)", code:"Pacific/Auckland"},
{name:"(GMT+11:00) Bougainville Standard Time (Pacific/Bougainville)", code:"Pacific/Bougainville"},
{name:"(GMT+12:45) Chatham Standard Time (Pacific/Chatham)", code:"Pacific/Chatham"},
{name:"(GMT+10:00) Chuuk Time (Pacific/Chuuk)", code:"Pacific/Chuuk"},
{name:"(GMT-6:00) Easter Is. Time (Pacific/Easter)", code:"Pacific/Easter"},
{name:"(GMT+11:00) Vanuatu Time (Pacific/Efate)", code:"Pacific/Efate"},
{name:"(GMT+13:00) Phoenix Is. Time (Pacific/Enderbury)", code:"Pacific/Enderbury"},
{name:"(GMT+13:00) Tokelau Time (Pacific/Fakaofo)", code:"Pacific/Fakaofo"},
{name:"(GMT+12:00) Fiji Time (Pacific/Fiji)", code:"Pacific/Fiji"},
{name:"(GMT+12:00) Tuvalu Time (Pacific/Funafuti)", code:"Pacific/Funafuti"},
{name:"(GMT-6:00) Galapagos Time (Pacific/Galapagos)", code:"Pacific/Galapagos"},
{name:"(GMT-9:00) Gambier Time (Pacific/Gambier)", code:"Pacific/Gambier"},
{name:"(GMT+11:00) Solomon Is. Time (Pacific/Guadalcanal)", code:"Pacific/Guadalcanal"},
{name:"(GMT+10:00) Chamorro Standard Time (Pacific/Guam)", code:"Pacific/Guam"},
{name:"(GMT-10:00) Hawaii Standard Time (Pacific/Honolulu)", code:"Pacific/Honolulu"},
{name:"(GMT-10:00) Hawaii Standard Time (Pacific/Johnston)", code:"Pacific/Johnston"},
{name:"(GMT+14:00) Line Is. Time (Pacific/Kiritimati)", code:"Pacific/Kiritimati"},
{name:"(GMT+11:00) Kosrae Time (Pacific/Kosrae)", code:"Pacific/Kosrae"},
{name:"(GMT+12:00) Marshall Islands Time (Pacific/Kwajalein)", code:"Pacific/Kwajalein"},
{name:"(GMT+12:00) Marshall Islands Time (Pacific/Majuro)", code:"Pacific/Majuro"},
{name:"(GMT-9:30) Marquesas Time (Pacific/Marquesas)", code:"Pacific/Marquesas"},
{name:"(GMT-11:00) Samoa Standard Time (Pacific/Midway)", code:"Pacific/Midway"},
{name:"(GMT+12:00) Nauru Time (Pacific/Nauru)", code:"Pacific/Nauru"},
{name:"(GMT-11:00) Niue Time (Pacific/Niue)", code:"Pacific/Niue"},
{name:"(GMT+11:30) Norfolk Time (Pacific/Norfolk)", code:"Pacific/Norfolk"},
{name:"(GMT+11:00) New Caledonia Time (Pacific/Noumea)", code:"Pacific/Noumea"},
{name:"(GMT-11:00) Samoa Standard Time (Pacific/Pago_Pago)", code:"Pacific/Pago_Pago"},
{name:"(GMT+9:00) Palau Time (Pacific/Palau)", code:"Pacific/Palau"},
{name:"(GMT-8:00) Pitcairn Standard Time (Pacific/Pitcairn)", code:"Pacific/Pitcairn"},
{name:"(GMT+11:00) Pohnpei Time (Pacific/Pohnpei)", code:"Pacific/Pohnpei"},
{name:"(GMT+11:00) Pohnpei Time (Pacific/Ponape)", code:"Pacific/Ponape"},
{name:"(GMT+10:00) Papua New Guinea Time (Pacific/Port_Moresby)", code:"Pacific/Port_Moresby"},
{name:"(GMT-10:00) Cook Is. Time (Pacific/Rarotonga)", code:"Pacific/Rarotonga"},
{name:"(GMT+10:00) Chamorro Standard Time (Pacific/Saipan)", code:"Pacific/Saipan"},
{name:"(GMT-11:00) Samoa Standard Time (Pacific/Samoa)", code:"Pacific/Samoa"},
{name:"(GMT-10:00) Tahiti Time (Pacific/Tahiti)", code:"Pacific/Tahiti"},
{name:"(GMT+12:00) Gilbert Is. Time (Pacific/Tarawa)", code:"Pacific/Tarawa"},
{name:"(GMT+13:00) Tonga Time (Pacific/Tongatapu)", code:"Pacific/Tongatapu"},
{name:"(GMT+10:00) Chuuk Time (Pacific/Truk)", code:"Pacific/Truk"},
{name:"(GMT+12:00) Wake Time (Pacific/Wake)", code:"Pacific/Wake"},
{name:"(GMT+12:00) Wallis & Futuna Time (Pacific/Wallis)", code:"Pacific/Wallis"},
{name:"(GMT+10:00) Chuuk Time (Pacific/Yap)", code:"Pacific/Yap"},
{name:"(GMT+1:00) Central European Time (Poland)", code:"Poland"},
{name:"(GMT0:00) Western European Time (Portugal)", code:"Portugal"},
{name:"(GMT+9:00) Korea Standard Time (ROK)", code:"ROK"},
{name:"(GMT+8:00) Singapore Time (Singapore)", code:"Singapore"},
{name:"(GMT-4:00) Atlantic Standard Time (SystemV/AST4)", code:"SystemV/AST4"},
{name:"(GMT-4:00) Atlantic Standard Time (SystemV/AST4ADT)", code:"SystemV/AST4ADT"},
{name:"(GMT-6:00) Central Standard Time (SystemV/CST6)", code:"SystemV/CST6"},
{name:"(GMT-6:00) Central Standard Time (SystemV/CST6CDT)", code:"SystemV/CST6CDT"},
{name:"(GMT-5:00) Eastern Standard Time (SystemV/EST5)", code:"SystemV/EST5"},
{name:"(GMT-5:00) Eastern Standard Time (SystemV/EST5EDT)", code:"SystemV/EST5EDT"},
{name:"(GMT-10:00) Hawaii Standard Time (SystemV/HST10)", code:"SystemV/HST10"},
{name:"(GMT-7:00) Mountain Standard Time (SystemV/MST7)", code:"SystemV/MST7"},
{name:"(GMT-7:00) Mountain Standard Time (SystemV/MST7MDT)", code:"SystemV/MST7MDT"},
{name:"(GMT-8:00) Pacific Standard Time (SystemV/PST8)", code:"SystemV/PST8"},
{name:"(GMT-8:00) Pacific Standard Time (SystemV/PST8PDT)", code:"SystemV/PST8PDT"},
{name:"(GMT-9:00) Alaska Standard Time (SystemV/YST9)", code:"SystemV/YST9"},
{name:"(GMT-9:00) Alaska Standard Time (SystemV/YST9YDT)", code:"SystemV/YST9YDT"},
{name:"(GMT+2:00) Eastern European Time (Turkey)", code:"Turkey"},
{name:"(GMT0:00) Coordinated Universal Time (UCT)", code:"UCT"},
{name:"(GMT-9:00) Alaska Standard Time (US/Alaska)", code:"US/Alaska"},
{name:"(GMT-10:00) Hawaii-Aleutian Standard Time (US/Aleutian)", code:"US/Aleutian"},
{name:"(GMT-7:00) Mountain Standard Time (US/Arizona)", code:"US/Arizona"},
{name:"(GMT-6:00) Central Standard Time (US/Central)", code:"US/Central"},
{name:"(GMT-5:00) Eastern Standard Time (US/East-Indiana)", code:"US/East-Indiana"},
{name:"(GMT-5:00) Eastern Standard Time (US/Eastern)", code:"US/Eastern"},
{name:"(GMT-10:00) Hawaii Standard Time (US/Hawaii)", code:"US/Hawaii"},
{name:"(GMT-6:00) Central Standard Time (US/Indiana-Starke)", code:"US/Indiana-Starke"},
{name:"(GMT-5:00) Eastern Standard Time (US/Michigan)", code:"US/Michigan"},
{name:"(GMT-7:00) Mountain Standard Time (US/Mountain)", code:"US/Mountain"},
{name:"(GMT-8:00) Pacific Standard Time (US/Pacific)", code:"US/Pacific"},
{name:"(GMT-8:00) Pacific Standard Time (US/Pacific-New)", code:"US/Pacific-New"},
{name:"(GMT-11:00) Samoa Standard Time (US/Samoa)", code:"US/Samoa"},
{name:"(GMT0:00) Coordinated Universal Time (UTC)", code:"UTC"},
{name:"(GMT0:00) Coordinated Universal Time (Universal)", code:"Universal"},
{name:"(GMT+3:00) Moscow Standard Time (W-SU)", code:"W-SU"},
{name:"(GMT0:00) Western European Time (WET)", code:"WET"},
{name:"(GMT0:00) Coordinated Universal Time (Zulu)", code:"Zulu"},
{name:"(GMT-5:00) Eastern Standard Time (EST)", code:"EST"},
{name:"(GMT-10:00) Hawaii Standard Time (HST)", code:"HST"},
{name:"(GMT-7:00) Mountain Standard Time (MST)", code:"MST"},
{name:"(GMT+9:30) Australian Central Standard Time (Northern Territory) (ACT)", code:"ACT"},
{name:"(GMT+10:00) Australian Eastern Standard Time (New South Wales) (AET)", code:"AET"},
{name:"(GMT-3:00) Argentine Time (AGT)", code:"AGT"},
{name:"(GMT+2:00) Eastern European Time (ART)", code:"ART"},
{name:"(GMT-9:00) Alaska Standard Time (AST)", code:"AST"},
{name:"(GMT-3:00) Brasilia Time (BET)", code:"BET"},
{name:"(GMT+6:00) Bangladesh Time (BST)", code:"BST"},
{name:"(GMT+2:00) Central African Time (CAT)", code:"CAT"},
{name:"(GMT-3:30) Newfoundland Standard Time (CNT)", code:"CNT"},
{name:"(GMT-6:00) Central Standard Time (CST)", code:"CST"},
{name:"(GMT+8:00) China Standard Time (CTT)", code:"CTT"},
{name:"(GMT+3:00) Eastern African Time (EAT)", code:"EAT"},
{name:"(GMT+1:00) Central European Time (ECT)", code:"ECT"},
{name:"(GMT-5:00) Eastern Standard Time (IET)", code:"IET"},
{name:"(GMT+5:30) India Standard Time (IST)", code:"IST"},
{name:"(GMT+9:00) Japan Standard Time (JST)", code:"JST"},
{name:"(GMT+13:00) West Samoa Standard Time (MIT)", code:"MIT"},
{name:"(GMT+4:00) Armenia Time (NET)", code:"NET"},
{name:"(GMT+12:00) New Zealand Standard Time (NST)", code:"NST"},
{name:"(GMT+5:00) Pakistan Time (PLT)", code:"PLT"},
{name:"(GMT-7:00) Mountain Standard Time (PNT)", code:"PNT"},
{name:"(GMT-4:00) Atlantic Standard Time (PRT)", code:"PRT"},
{name:"(GMT-8:00) Pacific Standard Time (PST)", code:"PST"},
{name:"(GMT+11:00) Solomon Is. Time (SST)", code:"SST"},
{name:"(GMT+7:00) Indochina Time (VST)", code:"VST"}]